### ISSUE TITLE
getSettingValue()

### ISSUE THREAD

**Issue by it-can** [rennokki/eloquent-settings#11]
Hi,

```getSettingValue()```, would it not make more sense to change the 2nd parameter to a default value? Just like Laravel does everywhere in the code? Also I think that casting a setting value is a bit weird (you save a casttype in the DB, why do you want to change it when fetching it?)

**Comment by rennokki** [comment]
By default, the `$castType` is set to null to differentiate if the user wants to get it the way it is in the database or not. This occurs when you store, for example, an integer (123) as a string (so you have 123 and 'string' in the db), but you want to cast it automatically in case you need it as an integer or float, for example, without having to use the `(integer)` or `(float)` casts in the PHP. It's not a must-have feature, but it is an way to help users retrieve and cast data at the same time.
